# Generated by Django 6.0.3 on 2026-04-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tripitinerary_delete_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripitinerary',
            name='members',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
