# Generated by Django 6.0.3 on 2026-04-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tripitinerary_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripitinerary',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
